fix: re-export a default export from a file as the default export
timocov/dts-bundle-generator pull request #183
Opened 2022-01-03 15:51 UTC by gamemaker1

### Description

This PR fixes a bug where dts-bundle-generator does not `export default` an expression when re-exporting the default export from another file.

### Related Issues

Fixes #182

---

- [x] Fix the bug first
- [x] Add a test case for the bug
- [ ] Add a test case for re-exporting the default export from an external package (https://github.com/timocov/dts-bundle-generator/issues/182#issuecomment-1003616947)
- [ ] Fix any failing tests

2022-01-03 15:54 UTC, gamemaker1 commented on src/bundle-generator.ts
> +				.filter((exportedExpression) => exportedExpression.exportedName === 'default')[0],
I think it's unlikely that this will be `undefined`, but I'll add a check anyways

2022-01-03 16:12 UTC, gamemaker1 commented
[This](https://github.com/timocov/dts-bundle-generator/tree/master/tests%2Fe2e%2Ftest-cases%2Fdefault-export-of-default-export) test also fails, but it is extremely similar to the test case for the bug.

2022-01-03 16:40 UTC, timocov commented on src/bundle-generator.ts
> +					const defaultExport = params.getDefaultExportForSourceFile(statement.getSourceFile());
Hm, have you tried to use `params.resolveIdentifier` for this? It looks like it does quite similar what you need here (it is used in this function to retrieve the same kind of value btw)

2022-01-03 18:10 UTC, timocov commented
> but it is extremely similar to the test case for the bug.

It is, yes, but it seems that a generated code right now is incorrect:

```diff
export default class MyClass {
}
       
export {
	MyClass as default,
};

export {};
```

as you can see, there are 2 exports with the same name `default` and [the compiler will raise an error](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBAE2AMwIYFcA28DGnUDOBcAsgJ4DC+RcA3gFAC+9crbc9oksd9AkOSqFihRCgzYANEwDc9TuGjxajGUA) in this case, so we need to fix this as well.

I'd say that for default exports we need to change a behaviour a bit - instead of having `export default` in places where it was originally, we can leave nodes unexported in-place and then use the new behaviour to export them. Thus, for this test case I'd say we need to receive the next output:

```ts
declare class MyClass {
}

export {
	MyClass as default,
};

export {};
```

But here we need to handle a case when a default export doesn't have a name. In this case it should be exported as is, i.e. with `export default`:

<details>
<summary>Input</summary>

**class.ts**:

```ts
export default class {}
```

**input.ts**:
```ts
export { default } from './class';
```
</details>

<details>
<summary>Output</summary>

```ts
export default class {
}

export {};
```
</details>

2022-01-03 18:12 UTC, timocov commented
Also, another interesting test case would be re-export default export from importable package - you can add the following line to https://github.com/timocov/dts-bundle-generator/blob/master/tests/e2e/test-cases/re-export-from-importable-module/input.ts:

```ts
export { default } from 'package-with-default-export';
```

And expected output for this should be the following in `output.d.ts`:

```ts
export { default } from "package-with-default-export";
```

2022-01-03 18:15 UTC, timocov commented
And probably the last test case I found for this might be the following:

**lib.ts**:

```ts
export const sayHello = (name: string) => {
	console.log(`Hello there, ${name}!`)
}

export default sayHello;
```

**input.ts**:

```ts
export { default } from './lib';
export { sayHello } from './lib';
```

**output.d.ts**:

```ts
export declare const sayHello: (name: string) => void;

export {
	sayHello as default,
};

export {};
```

2022-01-03 18:25 UTC, timocov commented
Based on that I'd say:

- if a node (class, function, etc) is declared in root source file and it is exported via `export default`, then it should have `export default` in this node's text
- if a node is declared not in root source file but exported via `export default` then it should have `export default` in its text only if it doesn't have a name (because otherwise it won't work)
- otherwise we should 1) strip both `export` and `default` keywords from a content for this node 2) add `{ name as default }` for such node

Another FYI: it seems that if a named node doesn't have `name` ([here](https://github.com/timocov/dts-bundle-generator/blob/520b76ecc46cc1ab0e1468848cdc76b4fe4e297e/src/bundle-generator.ts#L768) or [here](https://github.com/timocov/dts-bundle-generator/blob/520b76ecc46cc1ab0e1468848cdc76b4fe4e297e/src/helpers/typescript.ts#L265)) and this node is exported via `export default`, we should use `DefaultKeyword` modifier from this node to get a symbol, so you can create a helper something like this:

```ts
export function getStatementNameNode(statement: ts.Node): ts.NamedDeclaration['name'] | ts.DefaultKeyword {
	const statementName = (statement as unknown as ts.NamedDeclaration).name;
	if (statementName === undefined) {
		const defaultModifier = statement.modifiers?.find((mod: ts.Modifier) => mod.kind === ts.SyntaxKind.DefaultKeyword);
		if (defaultModifier !== undefined) {
			return defaultModifier as ts.DefaultKeyword;
		}
	}

	return statementName;
}
```

and use it instead of `(node as unknown as ts.NamedDeclaration).name` in cases above.

2022-01-04 13:52 UTC, gamemaker1 commented on src/bundle-generator.ts
> +					const defaultExport = params.getDefaultExportForSourceFile(statement.getSourceFile());
That worked, thanks! Should have noticed it when I was poking around 🤦🏾

2022-01-04 13:57 UTC, gamemaker1 commented
> And probably the last test case I found for this might be the following...

https://github.com/timocov/dts-bundle-generator/pull/183#issuecomment-1004267667

I added this and it works!

2022-01-04 16:29 UTC, gamemaker1 commented
Working on [this](https://github.com/timocov/dts-bundle-generator/pull/183#issuecomment-1004266341) now

2022-01-05 11:25 UTC, gamemaker1 commented
Yay I got https://github.com/timocov/dts-bundle-generator/pull/183#issuecomment-1004266341 working (i.e., we don't touch `export { default }`s from external node modules anymore)

Will work on [this](https://github.com/timocov/dts-bundle-generator/pull/183#issuecomment-1004273260) now.

2022-01-05 16:50 UTC, timocov commented on src/bundle-generator.ts
> +					if (!isDeclarationFromExternalModule(params.resolveIdentifier(exportItem.name)!.getSourceFile())) {
I think this could be fixed easier by putting `continue` to [this if statement](https://github.com/timocov/dts-bundle-generator/pull/183/files#diff-5554c0b3649d68de687551481713522cf40d31aa531ea9fb666d71a8ba7afe71R441-R443) (right before this loop) - here we already check that `isReExportFromImportable` and add a statement to result array so it seems that we can skip the later processing there.

2022-01-06 07:58 UTC, gamemaker1 commented on src/bundle-generator.ts
> +					if (!isDeclarationFromExternalModule(params.resolveIdentifier(exportItem.name)!.getSourceFile())) {
But I need to leave only `export {default}`s untouched, so the if statement needs to be inside the loop right?

2022-01-06 11:41 UTC, gamemaker1 commented
Hi @timocov,

I need some help with the following:

> otherwise we should 1) strip both export and default keywords from a content for this node 2) add { name as default } for such node

`statement.modifiers` is a readonly field - and even if I temporarily suppress that error, removing the `export` and `default` modifiers means that the node is not prefixed with `declare` in the `.d.ts` file.

I have pushed the code I have tried out so far - let me know if I'm going in the right direction.

Thanks :)

2022-01-06 12:41 UTC, timocov commented
[This function](https://github.com/timocov/dts-bundle-generator/blob/520b76ecc46cc1ab0e1468848cdc76b4fe4e297e/src/bundle-generator.ts#L423-L485) processes the root source, i.e. a source file you provide as an entry point. [In this code](https://github.com/timocov/dts-bundle-generator/blob/520b76ecc46cc1ab0e1468848cdc76b4fe4e297e/src/bundle-generator.ts#L436-L443) we're going through all statements in this root file and check whether a statement is `export =` or `export {} from ''`.
If it is `export =` then we should add this statement to the result as is without any modification.
If it is `export {} from` statement _and_ the package where we have re-export from is importable (i.e. we must not inline it and should use import/export statements to handle it), then we should leave this statement as is as well.
But it seems that accidentally I forget to add `continue` at the end of this `if` statement. So if we add a statement to the result list of statement we don't need to processed with this statement any more.

> The statement.modifiers field is readonly, so I cannot modify it manually.

Yep. To apply some modifications to the result output the tool has a few helpers, which are provided to generate output function.

For example, [needStripDefaultKeywordForStatement](https://github.com/timocov/dts-bundle-generator/blob/520b76ecc46cc1ab0e1468848cdc76b4fe4e297e/src/bundle-generator.ts#L259-L268) allows you to tell whether a `default` keyword should be stripped from the output of a node. So here you can just returned true or false and the tool will handle for you the rest.

Also, there is another helper [shouldStatementHasExportKeyword](https://github.com/timocov/dts-bundle-generator/blob/520b76ecc46cc1ab0e1468848cdc76b4fe4e297e/src/bundle-generator.ts#L270-L307), which is used to detect whether a node/statement should have an `export` keyword at the beginning of the node.

As you can see, in both functions ([here](https://github.com/timocov/dts-bundle-generator/blob/520b76ecc46cc1ab0e1468848cdc76b4fe4e297e/src/bundle-generator.ts#L267) and [here](https://github.com/timocov/dts-bundle-generator/blob/520b76ecc46cc1ab0e1468848cdc76b4fe4e297e/src/bundle-generator.ts#L284-L285)) we're dealing with default export as a special case.

You can play with these 2 functions by returning different values and see how the result is affected. But I believe that the final result in both functions should be something like I described in https://github.com/timocov/dts-bundle-generator/pull/183#issuecomment-1004273260.

Let me know if I need to elaborate anything else.

2022-01-06 14:11 UTC, gamemaker1 commented
Thanks a lot for the detailed explanation, its really helpful <3

> But it seems that I accidentally forgot to add the `continue` at the end of this if statement.

Should I add one? It seems to be the intended behaviour anyways.

2022-01-06 15:20 UTC, timocov commented
> Should I add one? It seems to be the intended behaviour anyways.

Yes, please. If you add it, it seems that you won't need to do anything else related to this particular issue (e.g. https://github.com/timocov/dts-bundle-generator/pull/183/files#diff-5554c0b3649d68de687551481713522cf40d31aa531ea9fb666d71a8ba7afe71R459-R462)

2022-01-10 20:01 UTC, timocov commented
Hey @gamemaker1, what's about the test case from https://github.com/timocov/dts-bundle-generator/pull/183#issuecomment-1004264790 (about default export with a name)?

2022-01-10 20:17 UTC, timocov requested changes

2022-01-10 20:17 UTC, timocov commented on src/helpers/typescript.ts
> +			return defaultModifier as unknown as ts.DeclarationName;
Hm, I don't think that it's safe to do this. I think we can change the returned type to `ts.NamedDeclaration['name'] | ts.DefaultKeyword` and use this type in `getDeclarationNameSymbol` and `getExportsForName`

2022-01-10 20:17 UTC, timocov commented on src/bundle-generator.ts
> +					return hasNoDefaultExport || (isNamedExport && !isPartOfRootSourceFile);
1. It seems that to check whether an exported with `default` node has a name or not you could check whether a found default export's original name is `default`: `defaultExport.originalName !== 'default'` where `defaultExport` is `statementExports.find((exp: SourceFileExport) => exp.exportedName === 'default')`
2. I think it would be better to change a check whether a node is from root source file by checking it's source file rather than it's filename: `statement.getSourceFile() !== rootSourceFile`

So it seems that these changes could like this:

```suggestion
					// a statement should have a 'default' keyword only if it it declared in the root source file
					// otherwise it will be re-exported via `export { name as default }`
					const defaultExport = statementExports.find((exp: SourceFileExport) => exp.exportedName === 'default');
					return defaultExport === undefined || defaultExport.originalName !== 'default' && statement.getSourceFile() !== rootSourceFile;
```

2022-01-10 20:17 UTC, timocov commented on src/bundle-generator.ts
> +		if (ts.isExportAssignment(statement) || isReExportFromImportableModule(statement)) {
would you mind to revert this changes? it seems that nothing was changed here

2022-01-10 20:17 UTC, timocov commented on src/bundle-generator.ts
> +					if (isDeclarationFromExternalModule(params.resolveIdentifier(exportItem.name)!.getSourceFile())) {
what this check is for? what did you want to check here?

2022-01-10 20:17 UTC, timocov commented on src/bundle-generator.ts
> +					result.renamedExports.push(`${resolvedIdentifier?.getText()} as default`);
what if node's name will be `undefined` so the result text will be `{ undefined as default }`? I think we need to add a test case for that, see the bottom section in this comment https://github.com/timocov/dts-bundle-generator/pull/183#issuecomment-1004264790

2022-01-10 20:17 UTC, timocov commented on src/bundle-generator.ts
> +					} else if (onlyDirectlyExportedShouldBeExported) {
it seems that it could be done easily. [in this code](https://github.com/timocov/dts-bundle-generator/blob/520b76ecc46cc1ab0e1468848cdc76b4fe4e297e/src/bundle-generator.ts#L280-L285) we check whether a node has any export which we should consider to treat as "truly-exported". So we can slightly modify so `shouldBeDefaultExportedDirectly` should be `true` only in case of `statement.getSourceFile() === rootSourceFile` and all this code could be reverted back.

2022-01-10 20:18 UTC, timocov commented
@gamemaker1 I left some comments to your changed. Also, could you fix lint issues as well? Thanks!

2022-01-11 12:08 UTC, gamemaker1 commented on src/helpers/typescript.ts
> +			return defaultModifier as unknown as ts.DeclarationName;
Done in `c64fdc2`!

2022-01-11 12:09 UTC, gamemaker1 commented on src/helpers/typescript.ts
> +			return defaultModifier as unknown as ts.DeclarationName;
Done in c64fdc2!

2022-01-11 12:10 UTC, gamemaker1 commented on src/bundle-generator.ts
> +		if (ts.isExportAssignment(statement) || isReExportFromImportableModule(statement)) {
Oh sorry about that I think I did that when I was trying to address [this](https://github.com/timocov/dts-bundle-generator/pull/183#discussion_r778977677) :/

2022-01-11 12:12 UTC, gamemaker1 commented on src/bundle-generator.ts
> +					if (isDeclarationFromExternalModule(params.resolveIdentifier(exportItem.name)!.getSourceFile())) {
As the comment above it says: 'Leave `export { default } from 'external-package'` untouched'.

It addresses [this](https://github.com/timocov/dts-bundle-generator/pull/183/files/2b5e78669c778fe2d6455e3733e3e47af28f6da9#diff-ca21252d7fdfc2b40e9ef36b94f6c1381bdcb18b48f374cb5f1bfc53dd67ff7bR7) test case and [this](https://github.com/timocov/dts-bundle-generator/pull/183#issuecomment-1004266341) comment.

2022-01-11 12:13 UTC, gamemaker1 commented on src/bundle-generator.ts
> +					if (isDeclarationFromExternalModule(params.resolveIdentifier(exportItem.name)!.getSourceFile())) {
It just checks if the string (here, 'external-package') is an external module or a file

2022-01-11 12:13 UTC, gamemaker1 commented on src/bundle-generator.ts
> +					result.renamedExports.push(`${resolvedIdentifier?.getText()} as default`);
Ooh I missed that test case, will add it now!

2022-01-11 12:33 UTC, gamemaker1 commented on src/bundle-generator.ts
> +					} else if (onlyDirectlyExportedShouldBeExported) {
Done!

2022-01-11 13:51 UTC, gamemaker1 commented on src/bundle-generator.ts
> +					result.renamedExports.push(`${resolvedIdentifier?.getText()} as default`);
Done in c7aba43!

2022-01-11 13:52 UTC, gamemaker1 commented
Fixed the lint issues and also added second the test case from https://github.com/timocov/dts-bundle-generator/pull/183#issuecomment-1004264790!

2022-01-11 19:28 UTC, timocov requested changes

2022-01-11 19:28 UTC, timocov commented on src/helpers/typescript.ts
> +export function getNodeName(node: ts.Node): ts.NamedDeclaration['name'] | ts.Modifier {
```suggestion
export function getNodeName(node: ts.Node): ts.NamedDeclaration['name'] | ts.DefaultKeyword {
```

2022-01-11 19:28 UTC, timocov commented on src/helpers/typescript.ts
> +export function getDeclarationNameSymbol(name: ts.DeclarationName | ts.Modifier, typeChecker: ts.TypeChecker): ts.Symbol | null {
```suggestion
export function getDeclarationNameSymbol(name: ts.DeclarationName | ts.DefaultKeyword, typeChecker: ts.TypeChecker): ts.Symbol | null {
```

2022-01-11 19:28 UTC, timocov commented on src/helpers/typescript.ts
> +	name: ts.NamedDeclaration['name'] | ts.Modifier
```suggestion
	name: ts.NamedDeclaration['name'] | ts.DefaultKeyword
```

2022-01-11 19:28 UTC, timocov commented on src/bundle-generator.ts
> +						continue;
could you please add a test case for that as well? it looks like a bug tbh

2022-01-11 19:28 UTC, timocov commented on src/bundle-generator.ts
> +					if (!exportedNode || isDeclarationFromExternalModule(exportedNode.getSourceFile())) {
```suggestion
					const exportedNode = params.resolveIdentifier(exportItem.name);
					if (exportedNode === undefined) {
```

from my understanding

> Leave `export { default } from 'external-package'` untouched

this is already handled by added a `continue` keyword above. do you have a case when this condition works as well?

2022-01-11 19:28 UTC, timocov commented on src/bundle-generator.ts
> +					if (!resolvedIdentifier) {
```suggestion
					if (resolvedIdentifier === undefined) {
```

2022-01-11 19:28 UTC, timocov commented on src/bundle-generator.ts
> +				// export { baz as propertyName }
haha, good catch! 😄

2022-01-11 19:33 UTC, timocov commented
Oops, it seems that I broke that pipeline so I have to fix now.

2022-01-11 19:52 UTC, timocov commented on src/bundle-generator.ts
> +						continue;
it seems that the case where the you're exporting unnamed default export without a name is not supported for now. I'll create a separate issue for this.

2022-01-11 19:55 UTC, timocov commented on src/bundle-generator.ts
> +						continue;
Here we go https://github.com/timocov/dts-bundle-generator/issues/185

2022-01-11 19:59 UTC, timocov approved these changes

2022-01-11 20:02 UTC, merged

2022-01-11 20:05 UTC, timocov commented
Many thanks @gamemaker1 for all your hard work on this!

2022-01-12 01:19 UTC, gamemaker1 commented
Thanks for your help on this PR @timocov!

2023-02-04 09:29 UTC, Githubrostro approved these changes