Improve support of non-relative imports in projects with a baseUrl
timocov/dts-bundle-generator pull request #219
Opened 2022-08-29 13:19 UTC by josh-

Thanks for all your work on this great project @timocov.

I noticed a small issue when using non-relative imports in TypeScript projects with a `baseUrl` configured. It appears that `resolveModuleFileName` treats all modules that isn't prefixed with a `.` [as an external node_module](https://github.com/timocov/dts-bundle-generator/blob/c88676269c37e23f2a070a24dd6f5d5f569e08aa/src/bundle-generator.ts#L586), which causes `needStripImportFromImportTypeNode` to not strip these generated `import()` statements.

For example, prior to this change, the result of the `import-from-non-relative-path-inferred-type` test would be:

```ts
export interface MyType {
	field: string;
}
export declare function test(): import("field/type").MyType;

export {};
```

The `import()` here is unnecessary since `MyType` is already defined in the declaration file, and should be stripped.

This PR currently resolves the issue described above by, when a `baseUrl` is defined, checking whether a module exists relative to that baseUrl, before falling back to `node_modules/${moduleName}/` if the module does not exist at that path.

2022-08-29 13:20 UTC, josh- commented on src/bundle-generator.ts
> +		const filePath = `${path.join(baseUrl, moduleName)}.ts`;
We may need to add other file extensions here too.

2022-09-04 11:07 UTC, timocov requested changes
Hi @josh-, sorry for the late reply. Thanks for contributing, please take a look the comments. It seems that it might be fixed in a more appropriate way

2022-09-04 11:07 UTC, timocov commented on src/bundle-generator.ts
> +		if (fs.existsSync(filePath)) {
I don't think that this is legit to be used here. Only the compiler might help/know whether a module exists or not and we have to rely on its API in this matter (see my another comment in `needStripImportFromImportTypeNode` function)

2022-09-04 11:07 UTC, timocov commented on src/bundle-generator.ts
> +					const moduleFileName = resolveModuleFileName(rootSourceFile.fileName, node.argument.literal.text, baseUrl);
Try to use `updateResultCommonParams.resolveReferencedModule` instead, I think that function is designed to get the module file name correctly by using the compiler's API instead of dirty hacks with the path.

2022-09-04 19:50 UTC, timocov commented
@josh- It seems that it is turning into something bigger than just one simple change (in my case it is more than 300 lines already and I still need to make some changes). I'll take it over and finish the fix. Thanks for you contribution! Let's keep this PR open for now (I'll use your commits and make changes on top of).

2022-09-05 00:24 UTC, josh- commented
> @josh- It seems that it is turning into something bigger than just one simple change (in my case it is more than 300 lines already and I still need to make some changes). I'll take it over and finish the fix. Thanks for you contribution! Let's keep this PR open for now (I'll use your commits and make changes on top of).

No worries at all, that sounds great!

2022-10-02 21:26 UTC, timocov commented
The issue will be fixed in #224

2022-10-02 23:04 UTC, closed without merging

2022-10-07 22:42 UTC, timocov commented
The fix has been released [in v7.0.0](https://github.com/timocov/dts-bundle-generator/releases/tag/v7.0.0).