fix: support type only imports
timocov/dts-bundle-generator pull request #321
Opened 2024-05-05 09:38 UTC by egilsster

Initial draft for fixing #320

2024-05-05 21:26 UTC, timocov requested changes
Hey @egilsster, thanks for your contribution, but it seems it might not solve the problem completely and might cause other issues instead (please see my review comment, lets discuss it there)

2024-05-05 21:26 UTC, timocov commented on src/generate-output.ts
> +				.join(', type ')
it looks like it can be replaced with just `import type {}` syntax instead?

2024-05-05 21:26 UTC, timocov commented on src/generate-output.ts
> +	}
This is what I was afraid of. this will produce wrong output in the following case (or similar, I didn't check exactly this code but it should give you the idea):

```ts
// index.ts
import { MyClass } from 'some-lib';
import { ParentType } from './other';

export class Foo extends MyClass {
    field: ParentType;
}
```

```ts
// other.ts
import { type MyClass } from 'some-lib';

export type ParentType = MyClass;
```

Technically if a type was used as a "value", then it should be imported as a "value" even if there are imports of as a "type". But on the other side, there are cases where you might have mixed imports and mixed usage, and then re-export of "type" import but if we import it as "value" then it might be re-exported with a wrong meaning:

```ts
// index.ts
import type { MyClass } from 'some-lib';
import { FooBar } from './other';

export type MyClassType = MyClass;
```

```ts
// other.ts
import { MyClass } from 'some-lib';

export class FooBar extends MyClass {}
```

In this case the output might be the following:

```ts
import { MyClass } from 'some-lib';

export type MyClassType = MyClass;
export class FooBar extends MyClass {}
```

which looks correct, but it might have implications in other places (I need to play with this more to give you an example if there is one). Or it could be

```ts
import type { MyClass } from 'some-lib';

export type MyClassType = MyClass;
export class FooBar extends MyClass {}
```

Which is broken because [`'FooBar' cannot be used as a value because it was imported using 'import type'`](https://www.typescriptlang.org/dev/bug-workbench/?#code/PTAEAEBMFMGMBsCGAnRAXAlgewHYC5Q1kBXaAKBAgGcALLAdwFEBbDNAo0iscWhltmmiQAYhnjQCGHDAAeAOkjy0VMtwgAzcdByJmk0FjQ1oyZauiyADlmRpQCRFSqgRWLACEUoAN4BfNUpwLQldfSkZS3MyDGYbO0IATytoX1d3L2RQP1ANZCxmUAByeWAjE2QigG4yS3j7NGTUgEFQAF50zxQautt7R2dQAFlEgGEkQcshGRc3Lqz-IA).

That's why https://github.com/timocov/dts-bundle-generator/issues/290 exists and why initially I thought that #320 is a duplicate and then re-opened, but it seems I'm leaning to think about it as about a duplicate aging based on said above...

The issue is that compiler doesn't tell you whether a symbol/node was originally value but was used a type or anything like that (see https://github.com/microsoft/TypeScript/issues/57032 for more context).

2024-05-05 21:26 UTC, timocov commented on tests/e2e/test-cases/preserve-type-imports/input.ts
> +import type { Diagnostic, AffectedFileResult as RenamedImport } from "typescript";
oh please try to avoid using types from any of dependencies - they tend to change between releases and it will cause tests to fail without changing (almost) anything. If you need some specific pattern of a package, you can add it here https://github.com/timocov/dts-bundle-generator/tree/master/tests/e2e/test-cases/node_modules or use any existing one there

2024-05-12 15:40 UTC, egilsster commented on src/generate-output.ts
> +	}
Great reply! Haven't had time to digest but can hopefully sit down and think about this and push something. Appreciated!

2024-10-07 09:09 UTC, egilsster commented
Don't have any bandwidth nor motivation to tackled this as of now so closing it to remove noise. It'll still get referenced in the issue so the comments are still beneficial.

2024-10-07 09:09 UTC, closed without merging